// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToWlUpbl8FCqD3WzLqliJFnAIFb8Dkrg',
    appId: '1:97443520596:web:9fe512cf90a964cc3f8dc1',
    messagingSenderId: '97443520596',
    projectId: 'splitsnap-b97f6',
    authDomain: 'splitsnap-b97f6.firebaseapp.com',
    storageBucket: 'splitsnap-b97f6.firebasestorage.app',
    measurementId: 'G-ND58J3Z3E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQZCW98zW6k7-qwZgUvmwTHgKA12KR4c',
    appId: '1:97443520596:android:1b92b17ad54a58d43f8dc1',
    messagingSenderId: '97443520596',
    projectId: 'splitsnap-b97f6',
    storageBucket: 'splitsnap-b97f6.firebasestorage.app',
    androidClientId: '97443520596-ae470r2s4skf4av22fbthf69nkp9igub.apps.googleusercontent.com',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDZQZCW98zW6k7-qwZgUvmwTHgKA12KR4c',
  //   appId: '1:97443520596:android:e55379e1bd9f33a73f8dc1',
  //   messagingSenderId: '97443520596',
  //   projectId: 'splitsnap-b97f6',
  //   storageBucket: 'splitsnap-b97f6.firebasestorage.app',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdwF8_SbJUz9SfScRy8f410KDWVIY2RHw',
    appId: '1:97443520596:ios:d2361dc1dea632963f8dc1',
    messagingSenderId: '97443520596',
    projectId: 'splitsnap-b97f6',
    storageBucket: 'splitsnap-b97f6.firebasestorage.app',
    iosClientId: '97443520596-mqq921ave38cotoo73j4tgdc6acehlhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdwF8_SbJUz9SfScRy8f410KDWVIY2RHw',
    appId: '1:97443520596:ios:d2361dc1dea632963f8dc1',
    messagingSenderId: '97443520596',
    projectId: 'splitsnap-b97f6',
    storageBucket: 'splitsnap-b97f6.firebasestorage.app',
    iosClientId: '97443520596-mqq921ave38cotoo73j4tgdc6acehlhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBToWlUpbl8FCqD3WzLqliJFnAIFb8Dkrg',
    appId: '1:97443520596:web:00bd524c6166ebda3f8dc1',
    messagingSenderId: '97443520596',
    projectId: 'splitsnap-b97f6',
    authDomain: 'splitsnap-b97f6.firebaseapp.com',
    storageBucket: 'splitsnap-b97f6.firebasestorage.app',
    measurementId: 'G-PYM94WJT0G',
  );
}
